### ISSUE TITLE
Error in zeros(nM, 5 * nQ) : dimensions must be a positive quantity

### ISSUE THREAD

**Issue by OAKryzhanovskij** [dhopp1/nowcastDFM#1]
Good day!

> library(nowcastDFM)
> 
> # estimate a DFM with one block for all variables
> output_dfm <- dfm(data, blocks = NA, p = 1, max_iter = 5000, threshold = 1e-05) 
Error in zeros(nM, 5 * nQ) : dimensions must be a positive quantity

Tell me, please, what could be the problem?
I tried version R 3.6.1 and R 4.1.3, different versions of matlab package.

**Comment by OAKryzhanovskij** [comment]
The problem was with the date format. Fixed it myself.

**Comment by RightHandOfDoom** [comment]
@OAKryzhanovskij I have the same issue - how did you fix it? 
Thanks !!
